name: Pull request integration testing

on:
  pull_request, synchronize

jobs:
  test:
    if: github.event.pull_request.draft == false
    name: 'Run linter and tests'
    runs-on: ubuntu-latest
    services:
      nats:
        image: nats
        ports:
          - 4222
        restart: unless-stopped
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 13
      - name: Install dependencies
        run: npm ci
      - name: Generate and build examples
        run: npm run test:examples:integration
        env: 
          NATS_HOST: nats
          NATS_PORT: ${{ job.services.redis.ports['6379'] }}
  