name: Pull request integration testing

on: 
  pull_request:
    types: [synchronize]

jobs:
  integration-tests:
    name: Integration tests - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Install dependencies
        run: npm install --loglevel verbose
      - name: Build the docker-compose stack
        run: cd examples && docker-compose up -d
      - name: Check running containers
        run: docker ps -a
      - if: steps.packagejson.outputs.exists == 'true'
        name: Generate new examples
        run: npm run generate:examples
      - if: steps.packagejson.outputs.exists == 'true'
        name: Test examples
        run: npm run test:examples
      - name: Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v1
  