name: Pull request testing

on:
  pull_request

jobs:
  check-linting:
    name: 'Run linter'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 13
      - name: Install dependencies
        run: npm ci
      - name: Run linter
        run: npm run lint
  test-integration:
    if: github.event.pull_request.draft == false
    name: 'Run integration tests on examples'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 13
      - name: Install dependencies
        run: npm ci
      - name: Build the docker-compose stack
        run: cd examples && docker-compose up -d
      - name: Check running containers
        run: docker ps -a
      - name: Build pubsub example and test clients can talk to each other
        run: |
          npm run generate:examples:pubSub
          npm run test:examples:integration:pubSub
      - name: Build request/reply example and test clients can talk to each other
        run: |
          npm run generate:examples:requestReply
          npm run test:examples:integration:requestReply
      - name: Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v1
  