name: Pull request integration testing

on: 
  pull_request:
    types: [synchronize]

jobs:
  test:
    if: github.event.pull_request.draft == false
    name: 'Run linter and tests'
    runs-on: ubuntu-latest
    services:
      nats:
        image: nats
        ports:
          - 4222
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 13
      - name: Install dependencies
        run: npm ci
      - name: Build pubsub example and test clients can talk to each other
        run: |
          npm run generate:examples:pubSub
          npm run test:examples:integration:pubSub
        env: 
          NATS_HOST: nats
          NATS_PORT: ${{ job.services.nats.ports['4222'] }}
      - name: Build request/reply example and test clients can talk to each other
        run: |
          npm run generate:examples:requestReply
          npm run test:examples:integration:requestReply
        env: 
          NATS_HOST: nats
          NATS_PORT: ${{ job.services.nats.ports['4222'] }}
  