name: Pull request integration testing

on: 
  pull_request:
    types: [synchronize]

jobs:
  test:
    if: github.event.pull_request.draft == false
    name: 'Run example tests'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 13
      - name: Install dependencies
        run: npm ci
      - name: Build the docker-compose stack
        run: cd examples && docker-compose up -d
      - name: Check running containers
        run: docker ps -a
      - name: Build pubsub example and test clients can talk to each other
        run: |
          npm run generate:examples:pubSub
          npm run test:examples:integration:pubSub
      - name: Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v1
  